/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-04-08 15:27:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pojo.Profilepojo;
import com.daoimpl.ProfileImpl;
import com.pojo.CustomizePojo;
import com.daoimpl.CustomizeDaoimpl;
import com.pojo.OrderPojo;
import com.daoimpl.OrdersDaoimpl;
import com.pojo.UserPojo;
import com.daoimpl.UserDaoimpl;
import com.pojo.CakePojo;
import java.util.List;
import com.daoimpl.CakeDaoimpl;
import com.pojo.CategoryPojo;
import java.util.List;
import com.daoimpl.CategoryDaoimpl;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/modal.jsp", Long.valueOf(1743510403226L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(18);
    _jspx_imports_classes.add("com.pojo.CustomizePojo");
    _jspx_imports_classes.add("com.pojo.OrderPojo");
    _jspx_imports_classes.add("com.daoimpl.CakeDaoimpl");
    _jspx_imports_classes.add("com.pojo.CakePojo");
    _jspx_imports_classes.add("com.daoimpl.OrdersDaoimpl");
    _jspx_imports_classes.add("com.pojo.UserPojo");
    _jspx_imports_classes.add("com.daoimpl.ProfileImpl");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.daoimpl.CustomizeDaoimpl");
    _jspx_imports_classes.add("com.pojo.CategoryPojo");
    _jspx_imports_classes.add("com.daoimpl.UserDaoimpl");
    _jspx_imports_classes.add("com.pojo.Profilepojo");
    _jspx_imports_classes.add("com.daoimpl.CategoryDaoimpl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Admin Dashboard - Cake Shop</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    	:root {\r\n");
      out.write("    --main-color: rgb(102, 67, 67);\r\n");
      out.write("    --nav-color: rgb(121, 87, 87);\r\n");
      out.write("    --bg-color: rgb(255, 240, 209);\r\n");
      out.write("    --black: rgb(59, 48, 48);\r\n");
      out.write("    --card-color: rgb(66, 36, 8);\r\n");
      out.write("    --theme: rgb(230, 201, 185);\r\n");
      out.write("    --border: .1rem solid var(--card-color);\r\n");
      out.write("    --box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    text-transform: capitalize;\r\n");
      out.write("    font-family: overlock, sans-serif;\r\n");
      out.write("    transition: all 0.2s ease-in;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("    font-size: 62.5%;\r\n");
      out.write("    overflow-x: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("    background-color: var(--bg-color);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar {\r\n");
      out.write("    height: 100vh;\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    background: var(--main-color);\r\n");
      out.write("    padding-top: 20px;\r\n");
      out.write("    transition: 0.3s;\r\n");
      out.write("    box-shadow: var(--box-shadow);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar h2 {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: var(--bg-color);\r\n");
      out.write("    font-size: 2.2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a {\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: var(--bg-color);\r\n");
      out.write("    font-size: 1.6rem;\r\n");
      out.write("    transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar a:hover {\r\n");
      out.write("    background: var(--nav-color);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("    margin-left: 250px;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    transition: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("    font-size: 3rem;\r\n");
      out.write("    color: var(--black);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card {\r\n");
      out.write("    background-color: var(--theme);\r\n");
      out.write("    padding: 2rem;\r\n");
      out.write("    border-radius: 1rem;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    box-shadow: var(--box-shadow);\r\n");
      out.write("    transition: transform 0.3s ease-in-out;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card:hover {\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card h5 {\r\n");
      out.write("    font-size: 2rem;\r\n");
      out.write("    color: var(--black);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card p {\r\n");
      out.write("    font-size: 1.8rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: var(--card-color);\r\n");
      out.write("}\r\n");
      out.write("    </style>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js\" defer></script>\r\n");
      out.write("   \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

CategoryDaoimpl categoryDaoimpl=new CategoryDaoimpl();
List<CategoryPojo> lcp=categoryDaoimpl.getAllCategory();

      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Add Cake</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <form action=\"AddCake_servlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("  <div class=\"mb-3\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\" class=\"form-label\">Name</label>\r\n");
      out.write("    <input type=\"text\" name=\"name\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"mb-3\">\r\n");
      out.write("    <label for=\"exampleInputPassword1\" class=\"form-label\">Price</label>\r\n");
      out.write("    <input type=\"number\" name=\"price\" class=\"form-control\" id=\"exampleInputPassword1\">\r\n");
      out.write("  </div>\r\n");
      out.write("<div class=\"mb-3\">\r\n");
      out.write("    <label for=\"exampleInputPassword1\" class=\"form-label\">discount</label>\r\n");
      out.write("    <input type=\"number\" name=\"discount\" class=\"form-control\" id=\"exampleInputPassword1\">\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"mb-3\">\r\n");
      out.write("    <label for=\"exampleInputPassword1\" class=\"form-label\">Fprice</label>\r\n");
      out.write("    <input type=\"number\" name=\"fprice\" class=\"form-control\" id=\"exampleInputPassword1\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"mb-3\">\r\n");
      out.write("      <label for=\"disabledSelect\" class=\"form-label\">Category</label>\r\n");
      out.write("      <select id=\"disabledSelect\" class=\"form-select\" name=\"category\">\r\n");
      out.write("      ");
for(CategoryPojo c:lcp){ 
      out.write("\r\n");
      out.write("        <option value=\"disable\">");
      out.print(c.getName() );
      out.write("</option>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("      </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\" class=\"form-label\">Description</label>\r\n");
      out.write("    <textarea rows=\"\" cols=\"\" class=\"form-control\" name=\"description\"></textarea>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"mb-3\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\" class=\"form-label\">Image</label>\r\n");
      out.write("    <input type=\"file\" class=\"form-control\" name=\"image\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">\r\n");
      out.write("  </div>\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-primary btn-block\">Add</button>\r\n");
      out.write("</form>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"categoryModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Add Category</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <form action=\"AddCategory_servlet\" method=\"post\">\r\n");
      out.write("  <div class=\"mb-3\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\" class=\"form-label\">Name</label>\r\n");
      out.write("    <input type=\"text\" name=\"name\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\">\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"mb-3\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\" class=\"form-label\">Description</label>\r\n");
      out.write("    <textarea rows=\"\" cols=\"\" class=\"form-control\" name=\"desc\"></textarea>\r\n");
      out.write("  </div>\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-primary btn-block\">Add</button>\r\n");
      out.write("</form>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("        <h2 class=\"text-center text-white\">Cake Admin</h2>\r\n");
      out.write("        <a href=\"admin.jsp\"><i class=\"fa fa-dashboard\"></i> Dashboard</a>\r\n");
      out.write("        <a href=\"admin.jsp?update=order\"><i class=\"fa fa-user\"></i>Orders</a>\r\n");
      out.write("        <a href=\"admin.jsp?update=user\"><i class=\"fa fa-user\"></i> All User</a>\r\n");
      out.write("        <a href=\"#\" data-bs-toggle=\"modal\" data-bs-target=\"#categoryModal\"><i class=\"fa fa-folder-plus\"></i> Add Category</a>\r\n");
      out.write("        <a href=\"#\"  data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\"><i class=\"fa fa-box\"></i> Add Cake</a>\r\n");
      out.write("        <a href=\"admin.jsp?update=cake\"><i class=\"fa fa-edit\"></i>All Cake</a>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    ");

    OrdersDaoimpl ordersDaoimpl=new OrdersDaoimpl();
    String email=(String)session.getAttribute("email");
    List<OrderPojo> lo=ordersDaoimpl.getOrdersByEmail(email);
    String u=request.getParameter("update");
    if(u==null){
    
      out.write("\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <h1>Dashboard</h1>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card p-3 shadow\">\r\n");
      out.write("                    <h5>Total Orders</h5>\r\n");
      out.write("                    <p>");
      out.print(ordersDaoimpl.totalOrders() );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card p-3 shadow\">\r\n");
      out.write("                    <h5>Total Revenue</h5>\r\n");
      out.write("                    <p>₹ ");
      out.print(ordersDaoimpl.totalRevenue() );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"card p-3 shadow\">\r\n");
      out.write("                    <h5>Total Cakes Sold</h5>\r\n");
      out.write("                    <p>");
      out.print(ordersDaoimpl.totalCakeSold() );
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
}
    else if(u.equals("cake")){
    	CakeDaoimpl cakeDaoimpl=new CakeDaoimpl();
        List<CakePojo> lc=cakeDaoimpl.getAllCake();
    	
    	
      out.write("\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("    <table class=\"table\">\r\n");
      out.write("  <thead>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"col\">#</th>\r\n");
      out.write("      <th scope=\"col\">Name</th>\r\n");
      out.write("      <th scope=\"col\">Price</th>\r\n");
      out.write("      <th scope=\"col\">Discount</th>\r\n");
      out.write("      <th scope=\"col\">DPrice</th>\r\n");
      out.write("      <th scope=\"col\">Category</th>\r\n");
      out.write("      <th scope=\"col\">image</th>\r\n");
      out.write("            <th scope=\"col\"></th>\r\n");
      out.write("      \r\n");
      out.write("            <th scope=\"col\"></th>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("  ");
for(CakePojo c:lc){ 
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\">1</th>\r\n");
      out.write("      <td>");
      out.print(c.getName() );
      out.write("</td>\r\n");
      out.write("      <td>₹ ");
      out.print(c.getPrice() );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print(c.getDiscount() );
      out.write(" %</td>\r\n");
      out.write("      <td>₹ ");
      out.print(c.getFprice() );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print(c.getCategory() );
      out.write("</td>\r\n");
      out.write("      <td><img src=\"images/cake/");
      out.print(c.getImage());
      out.write("\" height=\"70px\" width=\"70px\"></td>\r\n");
      out.write("     <td><a href=\"updateCake.jsp?cid=");
      out.print(c.getId());
      out.write("\"><button class=\"btn btn-outline-success\">Edit</button></a></td>\r\n");
      out.write("         <td><a href=\"DeleteCake_servlet?cid=");
      out.print(c.getId());
      out.write("\"><button class=\"btn btn-outline-danger\">Delete</button></a></td>\r\n");
      out.write("    \r\n");
      out.write("    </tr>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");
}else if(u.equals("order")){
    	
    	CustomizeDaoimpl customizeDaoimpl=new CustomizeDaoimpl();
    	
    	List<CustomizePojo> lcup=customizeDaoimpl.getAllCustomizeByEmail(email);
    	ProfileImpl profileImpl=new ProfileImpl();
    	Profilepojo profilepojo=profileImpl.getProfileByEmail(email);
    	
    	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     <div class=\"content\">\r\n");
      out.write("    <table class=\"table\">\r\n");
      out.write("  <thead>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"col\">#</th>\r\n");
      out.write("      <th scope=\"col\">Name</th>\r\n");
      out.write("      <th scope=\"col\">price</th>\r\n");
      out.write("      <th scope=\"col\">quantity</th>\r\n");
      out.write("      <th scope=\"col\">Tprice</th>\r\n");
      out.write("      <th scope=\"col\">Date</th>\r\n");
      out.write("      <th scope=\"col\">Address</th>\r\n");
      out.write("      <th scope=\"col\">Payment_id</th>\r\n");
      out.write("      \r\n");
      out.write("            \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("  ");
for(OrderPojo c:lo){ 
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\">");
      out.print(c.getId() );
      out.write("</th>\r\n");
      out.write("      <td>");
      out.print(c.getPname() );
      out.write("</td>\r\n");
      out.write("      <td> ");
      out.print(c.getPrice());
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print(c.getQuantity());
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print(c.getTprice() );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print(c.getDate() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print(c.getAddress() );
      out.write("</td>\r\n");
      out.write("      \r\n");
      out.write("            <td>");
      out.print(c.getPid() );
      out.write("</td>\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("    </tr>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("    <table class=\"table\">\r\n");
      out.write("  <thead>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"col\">#</th>\r\n");
      out.write("      <th scope=\"col\">Name</th>\r\n");
      out.write("      <th scope=\"col\">price</th>\r\n");
      out.write("      <th scope=\"col\">quantity</th>\r\n");
      out.write("      <th scope=\"col\">Tprice</th>\r\n");
      out.write("   <!--    <th scope=\"col\">Date</th> -->\r\n");
      out.write("      <th scope=\"col\">detail</th>\r\n");
      out.write("      <th scope=\"col\">Address</th>\r\n");
      out.write("      \r\n");
      out.write("            \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("  ");
for(CustomizePojo c:lcup){ 
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\">");
      out.print(c.getId() );
      out.write("</th>\r\n");
      out.write("      <td>Customize cake</td>\r\n");
      out.write("      <td>1200</td>\r\n");
      out.write("      <td>1</td>\r\n");
      out.write("      <td>1200</td>\r\n");
      out.write("      <td>");
      out.print(c.getDetail() );
      out.write("</td>\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("            <td>");
      out.print(profilepojo.getStreet() );
      out.write("</td>\r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("    </tr>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
}else{ 
    UserDaoimpl userDaoimpl=new UserDaoimpl();
    List<UserPojo> lup=userDaoimpl.getAllUser();
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("     <div class=\"content\">\r\n");
      out.write("    <table class=\"table\">\r\n");
      out.write("  <thead>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"col\">#</th>\r\n");
      out.write("      <th scope=\"col\">First Name</th>\r\n");
      out.write("      <th scope=\"col\">Last Name</th>\r\n");
      out.write("      <th scope=\"col\">Conatct No</th>\r\n");
      out.write("      <th scope=\"col\">Email</th>\r\n");
      out.write("      <th scope=\"col\">Password</th>\r\n");
      out.write("      \r\n");
      out.write("            <th scope=\"col\"></th>\r\n");
      out.write("      \r\n");
      out.write("            <th scope=\"col\"></th>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("  ");
for(UserPojo c:lup){ 
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"row\">");
      out.print(c.getUid() );
      out.write("</th>\r\n");
      out.write("      <td>");
      out.print(c.getFname() );
      out.write("</td>\r\n");
      out.write("      <td> ");
      out.print(c.getLname());
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print(c.getConatct() );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print(c.getEmail() );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print(c.getPassword() );
      out.write("</td>\r\n");
      out.write("     <td><a href=\"updateUser.jsp?cid=");
      out.print(c.getUid());
      out.write("\"><button class=\"btn btn-outline-success\">Edit</button></a></td>\r\n");
      out.write("         <td><a href=\"DeleteUser_servlet?cid=");
      out.print(c.getUid());
      out.write("\"><button class=\"btn btn-outline-danger\">Delete</button></a></td>\r\n");
      out.write("    \r\n");
      out.write("    </tr>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\" integrity=\"sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js\" integrity=\"sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
