/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-02-17 11:52:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pojo.CakePojo;
import com.daoimpl.CakeDaoimpl;

public final class cakedetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1737265382670L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.daoimpl.CakeDaoimpl");
    _jspx_imports_classes.add("com.pojo.CakePojo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Product Detail - Cake Shop</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js\" defer></script>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- <style>\r\n");
      out.write("    :root {\r\n");
      out.write("    --main-color: rgb(102, 67, 67);\r\n");
      out.write("    --nav-color: rgb(121, 87, 87);\r\n");
      out.write("    --bg-color: rgb(255, 240, 209);\r\n");
      out.write("    --black: rgb(59, 48, 48);\r\n");
      out.write("    --card-color: rgb(66, 36, 8);\r\n");
      out.write("    --theme: rgb(230, 201, 185);\r\n");
      out.write("    --border: .1rem solid var(var(--card-color));\r\n");
      out.write("    --box-shadow: (0 0 20px rgb(0, 0, 0));\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("        body {\r\n");
      out.write("            font-family: overlock;\r\n");
      out.write("            background-color: var(--bg-color);\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        *{\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: inherit;\r\n");
      out.write("    border: none;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    text-transform: capitalize;\r\n");
      out.write("    /* font-family: Verdana, Geneva, Tahoma, sans-serif; */\r\n");
      out.write("    font-family: overlock;\r\n");
      out.write("    transition: all 0.2s ease-in;\r\n");
      out.write("    /* scroll-behavior: smooth; */\r\n");
      out.write("    scroll-padding-top: 16vh;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("    background-color: var(--bg-color);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        .sidebar {\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            background: #ff6b6b;\r\n");
      out.write("            padding-top: 20px;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar a {\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar a:hover {\r\n");
      out.write("            background: #ff4f4f;\r\n");
      out.write("        }\r\n");
      out.write("        .content {\r\n");
      out.write("            margin-left: 250px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            transition: 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        .product-image {\r\n");
      out.write("            max-width: 100%;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .card {\r\n");
      out.write("            transition: transform 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </style> -->\r\n");
      out.write("    \r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("    .myrow{\r\n");
      out.write("    margin-top: 100px;\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("        <a href=\"\" class=\"logo\"><img src=\"images/logo.png\" alt=\"\"></a>\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">Home</a>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">Cakes</a>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">Customize Cakes</a>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">About Us</a>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">Contact Us</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"icons\">\r\n");
      out.write("            <div class=\"search-icon\"><i class=\"fa-solid fa-magnifying-glass\"></i></div>\r\n");
      out.write("            <a href=\"cart.jsp\"><div class=\"cart-icon\"><i class=\"fa-solid fa-cart-arrow-down\"></i></div></a>\r\n");
      out.write("            <div class=\"menu-icon\"><i class=\"fa-solid fa-bars\"></i></div>\r\n");
      out.write("            <!-- <a href=\"registration.html\">\r\n");
      out.write("                <div class=\"login-icon\"><i class=\"fa-solid fa-user\"></i></div>\r\n");
      out.write("            </a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"search-form\">\r\n");
      out.write("            <input type=\"search\" name=\"search\" id=\"search-box\" placeholder=\"search here...\">\r\n");
      out.write("            <label for=\"search-box\" class=\"fa-solid fa-magnifying-glass\"></label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cart-items-container\">\r\n");
      out.write("            <!-- first item -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"brownie.webp\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>brownie</h1>\r\n");
      out.write("                    <div class=\"price\">rs99/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- second item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"pcake.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>pineapple Cake</h1>\r\n");
      out.write("                    <div class=\"price\">rs300/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- third item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"ccake.jpeg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>choclate Cake</h1>\r\n");
      out.write("                    <div class=\"price\">rs450/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- fourth item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"cball.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>choclate balls</h3>\r\n");
      out.write("                    <div class=\"price\">rs200/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"\" class=\"btn\">order now</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    int cid=Integer.parseInt(request.getParameter("cid"));
    CakeDaoimpl cakeDaoimpl=new CakeDaoimpl();
    CakePojo cakePojo=cakeDaoimpl.getCakeById(cid);
    
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row  myrow\">\r\n");
      out.write("            <div class=\"col-md-5\">\r\n");
      out.write("                <img src=\"images/cake/");
      out.print(cakePojo.getImage() );
      out.write("\" alt=\"Cake Image\" class=\"product-image\" height=\"380px\"><br>\r\n");
      out.write("                <a href=\"AddCart_servlet?pid=");
      out.print(cakePojo.getId());
      out.write("\"><button class=\"btn btn-warning\" style=\"width: 84%;height: 40px;font-size: 20px;font-weight: 900;color:white;\">Add To Cart</button></a><br>\r\n");
      out.write("            	<button class=\"btn btn-warning\" style=\"width: 84%;height: 40px;font-size: 20px;font-weight: 900;color:white; margin-top:5px;\">Buy Now</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-7 \">\r\n");
      out.write("                <h2>");
      out.print(cakePojo.getName() );
      out.write("</h2>\r\n");
      out.write("                \r\n");
      out.write("                <p><strong>rs</strong>");
      out.print(cakePojo.getPrice() );
      out.write("</p>\r\n");
      out.write("                <p><strong>Description:</strong>");
      out.print(cakePojo.getDescription() );
      out.write("</p>\r\n");
      out.write("                \r\n");
      out.write("            <div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("        <script src=\"script.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
