/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-02-24 02:58:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pojo.Profilepojo;
import com.daoimpl.ProfileImpl;
import com.pojo.CartPojo;
import java.util.List;
import com.daoimpl.CartDaoimpl;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/message.jsp", Long.valueOf(1735911354380L));
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1737265382670L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("com.daoimpl.ProfileImpl");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.pojo.CartPojo");
    _jspx_imports_classes.add("com.daoimpl.CartDaoimpl");
    _jspx_imports_classes.add("com.pojo.Profilepojo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Cart - Food Delivery</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body { background-color: #fff0d1; font-family: 'Overlock', sans-serif; }\r\n");
      out.write("        .cart-header, .total-section { background-color: #e6c9b9; margin-top: 78px; padding: 8px; border-radius: 5px; box-shadow: 0 0 20px rgb(0, 0, 0); }\r\n");
      out.write("        .cart-item { border-bottom: 1px solid #423008; padding: 15px 0; display: flex; align-items: center; justify-content: space-between; }\r\n");
      out.write("        .checkout-btn { background-color: rgb(102, 67, 67); color: #fff0d1; border: none; width: 100%; padding: 10px; font-size: 1.2rem; border-radius: 5px; cursor: pointer; transition: 0.3s; }\r\n");
      out.write("        .checkout-btn:hover { background-color: rgb(121, 87, 87); }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

    String email = (String) session.getAttribute("email");
    CartDaoimpl cartDaoimpl = new CartDaoimpl();
    List<CartPojo> lc = cartDaoimpl.getCartByEmail(email);
    float tprice = cartDaoimpl.getTotalCartPriceByEmail(email);
    float originalPrice = cartDaoimpl.getTotalOriginalCartPriceByEmail(email);
    float discount = originalPrice - tprice;
    ProfileImpl profileImpl = new ProfileImpl();
    Profilepojo p = profileImpl.getProfileByEmail(email);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container my-4\">\r\n");
      out.write("    ");
      out.write("<header class=\"header\">\r\n");
      out.write("        <a href=\"\" class=\"logo\"><img src=\"images/logo.png\" alt=\"\"></a>\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">Home</a>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">Cakes</a>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">Customize Cakes</a>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">About Us</a>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">Contact Us</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"icons\">\r\n");
      out.write("            <div class=\"search-icon\"><i class=\"fa-solid fa-magnifying-glass\"></i></div>\r\n");
      out.write("            <a href=\"cart.jsp\"><div class=\"cart-icon\"><i class=\"fa-solid fa-cart-arrow-down\"></i></div></a>\r\n");
      out.write("            <div class=\"menu-icon\"><i class=\"fa-solid fa-bars\"></i></div>\r\n");
      out.write("            <!-- <a href=\"registration.html\">\r\n");
      out.write("                <div class=\"login-icon\"><i class=\"fa-solid fa-user\"></i></div>\r\n");
      out.write("            </a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"search-form\">\r\n");
      out.write("            <input type=\"search\" name=\"search\" id=\"search-box\" placeholder=\"search here...\">\r\n");
      out.write("            <label for=\"search-box\" class=\"fa-solid fa-magnifying-glass\"></label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cart-items-container\">\r\n");
      out.write("            <!-- first item -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"brownie.webp\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>brownie</h1>\r\n");
      out.write("                    <div class=\"price\">rs99/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- second item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"pcake.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>pineapple Cake</h1>\r\n");
      out.write("                    <div class=\"price\">rs300/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- third item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"ccake.jpeg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>choclate Cake</h1>\r\n");
      out.write("                    <div class=\"price\">rs450/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- fourth item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"cball.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>choclate balls</h3>\r\n");
      out.write("                    <div class=\"price\">rs200/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"\" class=\"btn\">order now</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    ");

String msg=(String)session.getAttribute("msg");
if(msg!=null){

      out.write("\r\n");
      out.write("<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("  <strong>");
      out.print(msg );
      out.write("</strong> \r\n");
      out.write("  <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
}
session.removeAttribute("msg");

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"cart-header d-flex justify-content-between align-items-center\">\r\n");
      out.write("        <h3>My Cart</h3>\r\n");
      out.write("        <a href=\"index.jsp\" class=\"btn btn-outline-secondary\">Continue Shopping</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"cart-items my-3 container\">\r\n");
      out.write("        ");
 for (CartPojo c : lc) { 
      out.write("\r\n");
      out.write("        <div class=\"cart-item row align-items-center\">\r\n");
      out.write("            <div class=\"col-md-2 col-3\">\r\n");
      out.write("                <img src=\"images/cake/");
      out.print(c.getImage() );
      out.write("\" alt=\"\" class=\"img-fluid rounded\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 col-6\">\r\n");
      out.write("                <h5>");
      out.print(c.getName() );
      out.write("</h5>\r\n");
      out.write("                <p>₹");
      out.print(c.getPrice() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 col-6\">\r\n");
      out.write("                <a href=\"quantityDecrease_servlet?cid=");
      out.print(c.getCid());
      out.write("\"><button class=\"btn btn-outline-secondary btn-sm\">-</button></a>\r\n");
      out.write("                <span>");
      out.print(c.getQuantity() );
      out.write("</span>\r\n");
      out.write("                <a href=\"quantityIncrease_servlet?cid=");
      out.print(c.getCid());
      out.write("\"><button class=\"btn btn-outline-secondary btn-sm\">+</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-6\">\r\n");
      out.write("                <p>₹");
      out.print(c.getTprice() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-2 col-6 text-end\">\r\n");
      out.write("                <a href=\"deleteCart_servlet?cid=");
      out.print(c.getCid());
      out.write("\"><button class=\"btn btn-danger btn-sm\">Remove</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"total-section mt-3\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("            <h5>Total</h5>\r\n");
      out.write("            <h5>₹");
      out.print( tprice );
      out.write("</h5>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        ");
 if (p.getEmail() == null) { 
      out.write("\r\n");
      out.write("            <button class=\"btn checkout-btn mt-3\" data-toggle=\"modal\" data-target=\"#errorModal\">Proceed to Checkout</button>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <form action=\"placeorder.jsp\" method=\"post\">\r\n");
      out.write("                <input type=\"hidden\" name=\"totalPrice\" value=\"");
      out.print( tprice );
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" name=\"originalPrice\" value=\"");
      out.print( originalPrice );
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" name=\"discount\" value=\"");
      out.print( discount );
      out.write("\">\r\n");
      out.write("                <input type=\"hidden\" name=\"email\" value=\"");
      out.print( email );
      out.write("\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn checkout-btn mt-3\">Proceed to Checkout</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
