/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-04-08 15:06:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pojo.Profilepojo;
import com.daoimpl.ProfileImpl;

public final class customized_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.daoimpl.ProfileImpl");
    _jspx_imports_classes.add("com.pojo.Profilepojo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Customized Cake Order</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Your provided CSS */\r\n");
      out.write("        :root {\r\n");
      out.write("            --main-color: rgb(102, 67, 67);\r\n");
      out.write("            --nav-color: rgb(121, 87, 87);\r\n");
      out.write("            --bg-color: rgb(255, 240, 209);\r\n");
      out.write("            --black: rgb(59, 48, 48);\r\n");
      out.write("            --card-color: rgb(66, 36, 8);\r\n");
      out.write("            --theme: rgb(230, 201, 185);\r\n");
      out.write("            --border: .1rem solid var(--card-color);\r\n");
      out.write("            --box-shadow: (0 0 20px rgb(0, 0, 0));\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: inherit;\r\n");
      out.write("            border: none;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            text-transform: capitalize;\r\n");
      out.write("            font-family: overlock;\r\n");
      out.write("            transition: all 0.2s ease-in;\r\n");
      out.write("            scroll-padding-top: 16vh;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        html {\r\n");
      out.write("            font-size: 62.5%;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: var(--bg-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        section {\r\n");
      out.write("            padding: 2rem 3%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .title {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: var(--card-color);\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            padding: 2rem 0;\r\n");
      out.write("            font-size: 4rem;\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .title span {\r\n");
      out.write("            color: var(--nav-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container {\r\n");
      out.write("            background-color: var(--theme);\r\n");
      out.write("            max-width: 50rem;\r\n");
      out.write("            margin: 2rem auto;\r\n");
      out.write("            padding: 2rem;\r\n");
      out.write("            border: var(--border);\r\n");
      out.write("            border-radius: 1rem;\r\n");
      out.write("            box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container h3 {\r\n");
      out.write("            color: var(--card-color);\r\n");
      out.write("            font-size: 3rem;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container .input-box {\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container .input-box label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            font-size: 1.6rem;\r\n");
      out.write("            color: var(--black);\r\n");
      out.write("            margin-bottom: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container .input-box input,\r\n");
      out.write("        .form-container .input-box textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 1rem;\r\n");
      out.write("            font-size: 1.6rem;\r\n");
      out.write("            color: var(--black);\r\n");
      out.write("            background-color: var(--bg-color);\r\n");
      out.write("            border: var(--border);\r\n");
      out.write("            border-radius: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container .input-box textarea {\r\n");
      out.write("            height: 10rem;\r\n");
      out.write("            resize: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container .btn {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            background-color: var(--main-color);\r\n");
      out.write("            color: var(--bg-color);\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            border-radius: 0.5rem;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container .btn:hover {\r\n");
      out.write("            letter-spacing: 0.1rem;\r\n");
      out.write("            background-color: var(--nav-color);\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String email=(String)session.getAttribute("email");
ProfileImpl profileImpl=new ProfileImpl();
Profilepojo profilepojo=profileImpl.getProfileByEmail(email);

      out.write("\r\n");
      out.write("    <section>\r\n");
      out.write("        <h2 class=\"title\">Order Your <span>Customized Cake</span></h2>\r\n");
      out.write("        <div class=\"form-container\">\r\n");
      out.write("            <form id=\"cakeForm\" action=\"Customize_servlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                <h3>Fill in the Details</h3>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <label for=\"name\">Name</label>\r\n");
      out.write("                    <input type=\"text\" id=\"name\" name=\"name\" value=\"");
      out.print(profilepojo.getName() );
      out.write("\" placeholder=\"Enter your name\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <label for=\"mobile\">Mobile</label>\r\n");
      out.write("                    <input type=\"tel\" id=\"mobile\" value=\"");
      out.print(profilepojo.getContact() );
      out.write("\" name=\"mobile\" placeholder=\"Enter your mobile number\" pattern=\"[0-9]{10}\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <label for=\"email\">Email</label>\r\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" value=\"");
      out.print(profilepojo.getEmail() );
      out.write("\" placeholder=\"Enter your email\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <label for=\"details\">Cake Details</label>\r\n");
      out.write("                    <textarea id=\"details\" name=\"detail\" placeholder=\"Write details about the cake (flavor, size, etc.)\" required></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-box\">\r\n");
      out.write("                    <label for=\"cakeImage\">Sample Image</label>\r\n");
      out.write("                    <input type=\"file\" id=\"cakeImage\" name=\"image\" accept=\"image/*\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"btn\" type=\"submit\">Place Order</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- <script>\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("            const isLoggedIn = true; // Replace with actual login check\r\n");
      out.write("            const form = document.getElementById('cakeForm');\r\n");
      out.write("            if (!isLoggedIn) {\r\n");
      out.write("                form.innerHTML = '<h3>Please log in to place an order</h3>';\r\n");
      out.write("            } else {\r\n");
      out.write("                form.addEventListener('submit', (e) => {\r\n");
      out.write("                    e.preventDefault();\r\n");
      out.write("                    alert('Order placed successfully!');\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script> -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
