/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-02-18 12:30:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pojo.Profilepojo;
import com.daoimpl.ProfileImpl;

public final class editprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/message.jsp", Long.valueOf(1735911354380L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.daoimpl.ProfileImpl");
    _jspx_imports_classes.add("com.pojo.Profilepojo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css\" integrity=\"sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link href=\"nav.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

String email=(String)session.getAttribute("email");
ProfileImpl profileimpl=new ProfileImpl();
Profilepojo profilepojo = profileimpl.getProfileByEmail(email);

      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"col-md-6 offset-md-3\">\r\n");

String msg=(String)session.getAttribute("msg");
if(msg!=null){

      out.write("\r\n");
      out.write("<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("  <strong>");
      out.print(msg );
      out.write("</strong> \r\n");
      out.write("  <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
}
session.removeAttribute("msg");

      out.write("\r\n");
      out.write("<div id=\"profile\" class=\"card\">\r\n");
      out.write("    <div class=\"card-body\">\r\n");
      out.write("    <form action=\"updateprofile_servlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">Name</label>\r\n");
      out.write("    <input type=\"text\" name=\"name\" value=\"");
      out.print(profilepojo.getName() );
      out.write("\" required=\"required\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Enter Name\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputPassword1\">Contact</label>\r\n");
      out.write("    <input type=\"tel\" name=\"contact\" value=\"");
      out.print(profilepojo.getContact() );
      out.write("\" required=\"required\" class=\"form-control\" id=\"exampleInputPassword1\" placeholder=\"Password\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleFormControlSelect1\">State</label>\r\n");
      out.write("    <select class=\"form-control\" name=\"state\" id=\"exampleFormControlSelect1\">\r\n");
      out.write("    <option>");
      out.print(profilepojo.getState() );
      out.write("</option>\r\n");
      out.write("       <option value=\"Andhra Pradesh\">Andhra Pradesh</option>\r\n");
      out.write("            <option value=\"Arunachal Pradesh\">Arunachal Pradesh</option>\r\n");
      out.write("            <option value=\"Assam\">Assam</option>\r\n");
      out.write("            <option value=\"Bihar\">Bihar</option>\r\n");
      out.write("            <option value=\"Chhattisgarh\">Chhattisgarh</option>\r\n");
      out.write("            <option value=\"Goa\">Goa</option>\r\n");
      out.write("            <option value=\"Gujarat\">Gujarat</option>\r\n");
      out.write("            <option value=\"Haryana\">Haryana</option>\r\n");
      out.write("            <option value=\"Himachal Pradesh\">Himachal Pradesh</option>\r\n");
      out.write("            <option value=\"Jharkhand\">Jharkhand</option>\r\n");
      out.write("            <option value=\"Karnataka\">Karnataka</option>\r\n");
      out.write("            <option value=\"Kerala\">Kerala</option>\r\n");
      out.write("            <option value=\"Madhya Pradesh\">Madhya Pradesh</option>\r\n");
      out.write("            <option value=\"Maharashtra\">Maharashtra</option>\r\n");
      out.write("            <option value=\"Manipur\">Manipur</option>\r\n");
      out.write("            <option value=\"Meghalaya\">Meghalaya</option>\r\n");
      out.write("            <option value=\"Mizoram\">Mizoram</option>\r\n");
      out.write("            <option value=\"Nagaland\">Nagaland</option>\r\n");
      out.write("            <option value=\"Odisha\">Odisha</option>\r\n");
      out.write("            <option value=\"Punjab\">Punjab</option>\r\n");
      out.write("            <option value=\"Rajasthan\">Rajasthan</option>\r\n");
      out.write("            <option value=\"Sikkim\">Sikkim</option>\r\n");
      out.write("            <option value=\"Tamil Nadu\">Tamil Nadu</option>\r\n");
      out.write("            <option value=\"Telangana\">Telangana</option>\r\n");
      out.write("            <option value=\"Tripura\">Tripura</option>\r\n");
      out.write("            <option value=\"Uttar Pradesh\">Uttar Pradesh</option>\r\n");
      out.write("            <option value=\"Uttarakhand\">Uttarakhand</option>\r\n");
      out.write("            <option value=\"West Bengal\">West Bengal</option>\r\n");
      out.write("            <option value=\"Andaman and Nicobar Islands\">Andaman and Nicobar Islands</option>\r\n");
      out.write("            <option value=\"Chandigarh\">Chandigarh</option>\r\n");
      out.write("            <option value=\"Dadra and Nagar Haveli and Daman and Diu\">Dadra and Nagar Haveli and Daman and Diu</option>\r\n");
      out.write("            <option value=\"Lakshadweep\">Lakshadweep</option>\r\n");
      out.write("            <option value=\"Delhi\">Delhi</option>\r\n");
      out.write("            <option value=\"Puducherry\">Puducherry</option>\r\n");
      out.write("       \r\n");
      out.write("    </select>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">City</label>\r\n");
      out.write("    <input type=\"text\" name=\"city\" value=\"");
      out.print(profilepojo.getCity() );
      out.write("\" required=\"required\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Enter City\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">Street</label>\r\n");
      out.write("    <input type=\"text\" name=\"street\" value=\"");
      out.print(profilepojo.getStreet() );
      out.write("\" required=\"required\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Enter house no,Bulding name,street\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">Pincode</label>\r\n");
      out.write("    <input type=\"number\" name=\"pincode\" value=\"");
      out.print(profilepojo.getPincode() );
      out.write("\" required=\"required\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Enter pincode\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">Landmark</label>\r\n");
      out.write("    <input type=\"text\" name=\"landmark\" value=\"");
      out.print(profilepojo.getLandmark() );
      out.write("\" required=\"required\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Enter Landmark\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleFormControlFile1\">Image</label>\r\n");
      out.write("    <input type=\"file\" name=\"image\" value=\"");
      out.print(profilepojo.getImage() );
      out.write("\" class=\"form-control-file\" id=\"exampleFormControlFile1\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <button type=\"submit\" class=\"btn nav-color text-white btn-block\">Submit</button>\r\n");
      out.write("</form>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
