/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-04-09 01:51:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.pojo.CakePojo;
import java.util.List;
import com.daoimpl.CakeDaoimpl;
import com.daoimpl.UserDaoimpl;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/message.jsp", Long.valueOf(1735911354380L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1737267868671L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.daoimpl.CakeDaoimpl");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.pojo.CakePojo");
    _jspx_imports_classes.add("com.daoimpl.UserDaoimpl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/74366baee4.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    \r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");

String email =(String)session.getAttribute("email");
UserDaoimpl userDaoimpl=new UserDaoimpl();
String fname=userDaoimpl.getUsernameByEmail(email);

      out.write("\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <a href=\"\" class=\"logo\"><img src=\"images/logo.png\" alt=\"\"></a>\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("            <a href=\"#home\">Home</a>\r\n");
      out.write("            <a href=\"#cakes\">Cakes</a>\r\n");
      out.write("            <a href=\"#best-sellers\">customize cakes</a>\r\n");
      out.write("            <a href=\"#about\">About us</a>\r\n");
      out.write("            <a href=\"#contact\">Contact us\r\n");
      out.write("            </a>\r\n");
      out.write("            <!-- <a href=\"login.html\" class=\"lr\">login</a>\r\n");
      out.write("            <a href=\"\" class=\"lr\">registration</a> -->\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"icons\">\r\n");
      out.write("            <div class=\"search-icon\"><i class=\"fa-solid fa-magnifying-glass\"></i></div>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"cart.jsp\"><div class=\"cart-icon\"><i class=\"fa-solid fa-cart-arrow-down\"></i></div></a>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"menu-icon\"><i class=\"fa-duotone fa-solid fa-bars\"></i></div>\r\n");
if(email==null){ 
      out.write("\r\n");
      out.write("            <a href=\"register.jsp\">\r\n");
      out.write("            <div class=\"login-icon\"><i class=\"fa-solid fa-user\"></i></div>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
}else{ 
      out.write("\r\n");
      out.write("        <a href=\"\" style=\"font-size:20px; color:black; text-decoration: none; margin-left: 10px;\">welcome ");
      out.print(fname );
      out.write("</a>\r\n");
      out.write("        <a href=\"Logout_servlet\"style=\"font-size:20px;color:black; text-decoration: none; margin-left: 10px;\">logout</a>\r\n");
      out.write("        \r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"search-form\">\r\n");
      out.write("            <input type=\"search\" name=\"search\" id=\"search-box\" placeholder=\"search here...\">\r\n");
      out.write("            <label for=\"search-box\" class=\"fa-solid fa-magnifying-glass\"></label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cart-items-container\">\r\n");
      out.write("            <!-- first item -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"images/brownie.webp\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>brownie</h1>\r\n");
      out.write("                    <div class=\"price\">rs99/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");

String msg=(String)session.getAttribute("msg");
if(msg!=null){

      out.write("\r\n");
      out.write("<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("  <strong>");
      out.print(msg );
      out.write("</strong> \r\n");
      out.write("  <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
}
session.removeAttribute("msg");

      out.write("\r\n");
      out.write("            <!-- second item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"images/pcake.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>pineapple Cake</h1>\r\n");
      out.write("                    <div class=\"price\">rs300/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- third item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"ccake.jpeg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>choclate Cake</h1>\r\n");
      out.write("                    <div class=\"price\">rs450/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- fourth item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"img/cball.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>choclate balls</h3>\r\n");
      out.write("                    <div class=\"price\">rs200/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"\" class=\"btn\">order now</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"home\" id=\"home\">\r\n");
      out.write("        <div class=\"hero\">\r\n");
      out.write("            <h3>From Oven to Heart Pure Delight in Every Bite!\r\n");
      out.write("            </h3>\r\n");
      out.write("            <p>\r\n");
      out.write("                At <b> bakery in the towm </b>, we take pride in being the sweetest spot in town. Our cakes are more\r\n");
      out.write("                than just desserts; they are handcrafted pieces of joy, made with the finest ingredients and a whole lot\r\n");
      out.write("                of love. From classic flavors to custom creations, each cake is baked fresh in our ovens to add a touch\r\n");
      out.write("                of magic to your celebrations. Whether it's a birthday, anniversary, or just a day to indulge, our cakes\r\n");
      out.write("                are here to make every moment unforgettable. Come visit us and taste the delight that everyone’s talking\r\n");
      out.write("                about!</p>\r\n");
      out.write("            <a class=\"btn\" href=\"\">get yous now</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");

CakeDaoimpl cakeDaoimpl=new CakeDaoimpl();
         List<CakePojo> lc= cakeDaoimpl.getAllCake();
         System.out.print(lc);

      out.write("\r\n");
      out.write("    <section class=\"cakes\" id=\"cakes\">\r\n");
      out.write("        <h3 class=\"title\">our <span>CAKES</span></h3>\r\n");
      out.write("        <div class=\"wrapper\">\r\n");
      out.write("            <!-- item one -->\r\n");
      out.write("            ");
for(CakePojo c:lc){ 
      out.write("\r\n");
      out.write("            <div class=\"cake-card\">\r\n");
      out.write("                <a href=\"cakedetail.jsp?cid=");
      out.print(c.getId());
      out.write("\"><img src=\"images/cake/");
      out.print(c.getImage() );
      out.write("\" alt=\"\"></a>\r\n");
      out.write("                <h3>");
      out.print(c.getName() );
      out.write("</h3>\r\n");
      out.write("                  <div class=\"price\">rs ");
      out.print(c.getFprice() );
      out.write("/-</div>\r\n");
      out.write("                <a href=\"AddCart_servlet?pid=");
      out.print(c.getId());
      out.write("\" class=\"btn\">add to cart</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <!-- item 2 -->\r\n");
      out.write("            <!-- <div class=\"cake-card\">\r\n");
      out.write("                <img src=\"caketwo.avif\" alt=\"\">\r\n");
      out.write("                <h3>pineapple cake</h3>\r\n");
      out.write("                <div class=\"price\">rs400/-</div>\r\n");
      out.write("                <a href=\"\" class=\"btn\">add to cart</a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            item 3\r\n");
      out.write("            <div class=\"cake-card\">\r\n");
      out.write("                <img src=\"cakethree.avif\" alt=\"\">\r\n");
      out.write("                <h3>choclate cake</h3>\r\n");
      out.write("                <div class=\"price\">rs400/-</div>\r\n");
      out.write("                <a href=\"\" class=\"btn\">add to cart</a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            item 4 \r\n");
      out.write("            <div class=\"cake-card\">\r\n");
      out.write("                <img src=\"cakefour.avif\" alt=\"\">\r\n");
      out.write("                <h3>vanilla cake</h3>\r\n");
      out.write("                <div class=\"price\">rs400/-</div>\r\n");
      out.write("                <a href=\"\" class=\"btn\">add to cart</a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            item 5\r\n");
      out.write("            <div class=\"cake-card\">\r\n");
      out.write("                <img src=\"cakefive.avif\" alt=\"\">\r\n");
      out.write("                <h3>red velate cake</h3>\r\n");
      out.write("                <div class=\"price\">rs400/- <span>rs500/-</span></div>\r\n");
      out.write("                <a href=\"\" class=\"btn\">add to cart</a>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            item 6\r\n");
      out.write("            <div class=\"cake-card\">\r\n");
      out.write("                <img src=\"cakesix.avif\" alt=\"\">\r\n");
      out.write("                <h3>strawberry cake</h3>\r\n");
      out.write("                <div class=\"price\">rs400/-</div>\r\n");
      out.write("                <a href=\"\" class=\"btn\">add to cart</a>\r\n");
      out.write("\r\n");
      out.write("            </div> -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- customized cakes -->\r\n");
      out.write("    <section class=\"best-sellers\" id=\"best-sellers\">\r\n");
      out.write("        <h1 class=\"title\"> customized <span> CAKES</span></h1>\r\n");
      out.write("        <div class=\"wrapper\">\r\n");
      out.write("            <!-- customized cake1 -->\r\n");
      out.write("            <div class=\"seller-card\">\r\n");
      out.write("                <div class=\"icons\">\r\n");
      out.write("                    <a class=\"fa-solid fa-cart-shopping\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-heart\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-bookmark\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"img\">\r\n");
      out.write("                    <img src=\"images/b1.avif\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>wedding cake</h3>\r\n");
      out.write("                    <a href=\"customized_form.jsp\" class=\"btn2\">customize yours</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- customized cake2 -->\r\n");
      out.write("            <div class=\"seller-card\">\r\n");
      out.write("                <div class=\"icons\">\r\n");
      out.write("                    <a class=\"fa-solid fa-cart-shopping\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-heart\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-bookmark\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"img\">\r\n");
      out.write("                    <img src=\"images/b2.avif\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>unicorn birthday cake</h3>\r\n");
      out.write("                    <a href=\"\" class=\"btn\">customize yours</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- customized cake3 -->\r\n");
      out.write("            <div class=\"seller-card\">\r\n");
      out.write("                <div class=\"icons\">\r\n");
      out.write("                    <a class=\"fa-solid fa-cart-shopping\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-heart\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-bookmark\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"img\">\r\n");
      out.write("                    <img src=\"images/b3.avif\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>frozen theme birthday cake</h3>\r\n");
      out.write("                    <a href=\"\" class=\"btn\">customize yours</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- customized cake4 -->\r\n");
      out.write("            <div class=\"seller-card\">\r\n");
      out.write("                <div class=\"icons\">\r\n");
      out.write("                    <a class=\"fa-solid fa-cart-shopping\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-heart\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-bookmark\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"img\">\r\n");
      out.write("                    <img src=\"images/b4.webp\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>jungle theme birthday cake</h3>\r\n");
      out.write("                    <a href=\"\" class=\"btn\">customize yours</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- customized cake5 -->\r\n");
      out.write("            <div class=\"seller-card\">\r\n");
      out.write("                <div class=\"icons\">\r\n");
      out.write("                    <a class=\"fa-solid fa-cart-shopping\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-heart\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-bookmark\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"img\">\r\n");
      out.write("                    <img src=\"images/b5.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>princess theme birthday cake</h3>\r\n");
      out.write("                    <a href=\"\" class=\"btn\">customize yours</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- customized cake6 -->\r\n");
      out.write("            <div class=\"seller-card\">\r\n");
      out.write("                <div class=\"icons\">\r\n");
      out.write("                    <a class=\"fa-solid fa-cart-shopping\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-heart\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-bookmark\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"img\">\r\n");
      out.write("                    <img src=\"images/b6.webp\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>ocene theme birthday cake</h3>\r\n");
      out.write("                    <a href=\"\" class=\"btn\">customize yours</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- customized cake7 -->\r\n");
      out.write("            <div class=\"seller-card\">\r\n");
      out.write("                <div class=\"icons\">\r\n");
      out.write("                    <a class=\"fa-solid fa-cart-shopping\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-heart\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-bookmark\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"img\">\r\n");
      out.write("                    <img src=\"images/b7.webp\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>ocene theme birthday cake</h3>\r\n");
      out.write("                    <a href=\"\" class=\"btn\">customize yours</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- customized cake8 -->\r\n");
      out.write("            <div class=\"seller-card\">\r\n");
      out.write("                <div class=\"icons\">\r\n");
      out.write("                    <a class=\"fa-solid fa-cart-shopping\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-heart\"></a>\r\n");
      out.write("                    <a class=\"fa-solid fa-bookmark\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"img\">\r\n");
      out.write("                    <img src=\"images/b8.jpeg\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>annivarsary cake</h3>\r\n");
      out.write("                    <a href=\"\" class=\"btn\">customize yours</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- about section -->\r\n");
      out.write("    <section class=\"about\" id=\"about\">\r\n");
      out.write("        <h1 class=\"title\"><span>ABOUT</span> us</h1>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"img\">\r\n");
      out.write("                <img src=\"images/shop.avif\" alt=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"content\">\r\n");
      out.write("                <h3>Bakery In Town\r\n");
      out.write("                </h3>\r\n");
      out.write("                <p>\r\n");
      out.write("                    Bakery In Town in Bhayandar East, Thane is a renowned bakery offering a delectable range of freshly baked goods and pastries. Situated in a prime location in Bhayandar, the bakery attracts food lovers from all over the area. Bakery In Town is a go-to destination for those looking to indulge in delightful baked treats.\r\n");
      out.write("                </p>\r\n");
      out.write("                <a href=\"\" class=\"btn\">learn more</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- /contact section -->\r\n");
      out.write("    <section class=\"contact\" id=\"contact\">\r\n");
      out.write("        <h1 class=\"title\"><span> CONTACT</span> us</h1>\r\n");
      out.write("        <div class=\"contents\">\r\n");
      out.write("            <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5189.7527598338975!2d72.84936261923824!3d19.308558805405188!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7b1d83619f689%3A0x43b7f783e4e9fee!2sBakery%20in%20town!5e0!3m2!1sen!2sin!4v1735451382802!5m2!1sen!2sin\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>\r\n");
      out.write("            <form action=\"\">\r\n");
      out.write("                <h3>get in touch</h3>\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <span class=\"fas fa-user\"></span>\r\n");
      out.write("                        <input type=\"text\" name=\"name\" placeholder=\"enter your name\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <span class=\"fas fa-envelope\"></span>\r\n");
      out.write("                        <input type=\"text\" name=\"email\" placeholder=\"enter your email\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"input-box\">\r\n");
      out.write("                        <span class=\"fas fa-phone\"></span>\r\n");
      out.write("                        <input type=\"tel\" name=\"phone\" placeholder=\"enter your contact number\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"\" class=\"btn\">contact now</a>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/74366baee4.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("     <footer class=\"footer\">\r\n");
      out.write("        <div class=\"social-media\">\r\n");
      out.write("    <a href=\"https://www.facebook.com/YourPageName\" class=\"fab fa-facebook-f text-decoration-none\" aria-label=\"Facebook\" target=\"_blank\" rel=\"noopener noreferrer\"></a>\r\n");
      out.write("    <a href=\"https://www.youtube.com/@Bakery-in-town\" class=\"fab fa-youtube text-decoration-none\" aria-label=\"YouTube\" target=\"_blank\" rel=\"noopener noreferrer\"></a>\r\n");
      out.write("    <a href=\"https://www.instagram.com/bakery_in_town_?igsh=ampvMjY2MWF3YnJh \" class=\"fab fa-instagram text-decoration-none\" aria-label=\"Instagram\" target=\"_blank\" rel=\"noopener noreferrer\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"links\">\r\n");
      out.write("            <a href=\"#home\" class=\"text-decoration-none\">Home</a>\r\n");
      out.write("            <a href=\"#cakes\" class=\"text-decoration-none\">Cakes</a>\r\n");
      out.write("            <a href=\"#best-sellers\" class=\"text-decoration-none\">customize cakes</a>\r\n");
      out.write("            <a href=\"#about\" class=\"text-decoration-none\">About us</a>\r\n");
      out.write("            <a href=\"#contact\" class=\"text-decoration-none\">Contact us\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("            <div class=\"credits\">\r\n");
      out.write("                created by <span>tanuja</span> | all rights reserved.\r\n");
      out.write("            </div>\r\n");
      out.write("     </footer>\r\n");
      out.write("     <script src=\"script.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script src=\"script.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
