/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-04-08 15:18:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.daoimpl.CustomizeDaoimpl;
import com.pojo.CustomizePojo;
import com.pojo.CartPojo;
import java.util.List;
import com.daoimpl.CartDaoimpl;

public final class placeorder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("com.pojo.CustomizePojo");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.pojo.CartPojo");
    _jspx_imports_classes.add("com.daoimpl.CustomizeDaoimpl");
    _jspx_imports_classes.add("com.daoimpl.CartDaoimpl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Place Order</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css\">\r\n");
      out.write("    <script src=\"https://checkout.razorpay.com/v1/checkout.js\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("        .accordion-button {\r\n");
      out.write("            background-color: #ff5200;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .accordion-button:active, .accordion-button:not(.collapsed) {\r\n");
      out.write("            background-color: #ff5200;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        .accordion-button:focus {\r\n");
      out.write("            box-shadow: none;\r\n");
      out.write("            border: 1px solid #043d14;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

    String email = (String) session.getAttribute("email");
    CartDaoimpl cartDao = new CartDaoimpl();
    List<CartPojo> cartItems = cartDao.getCartByEmail(email);
    float totalPrice = cartDao.getTotalCartPriceByEmail(email) * 100; // Convert to paisa
	String cu=request.getParameter("cus");
    CustomizeDaoimpl customizeDaoimpl=new CustomizeDaoimpl();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-12\">\r\n");
      out.write("            <div class=\"accordion\" id=\"orderAccordion\">\r\n");
      out.write("                <div class=\"accordion-item\">\r\n");
      out.write("                    <h2 class=\"accordion-header\" id=\"orderSummaryHeading\">\r\n");
      out.write("                        <button class=\"accordion-button\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#orderSummary\" aria-expanded=\"true\" aria-controls=\"orderSummary\">\r\n");
      out.write("                            <b style=\"font-size:20px;\">Order Summary</b>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </h2>\r\n");
      out.write("                    <div id=\"orderSummary\" class=\"accordion-collapse collapse show\" aria-labelledby=\"orderSummaryHeading\">\r\n");
      out.write("                        <div class=\"accordion-body\">\r\n");
      out.write("                            <table class=\"table\">\r\n");
      out.write("                                <thead>\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <th scope=\"col\">Item Name</th>\r\n");
      out.write("                                        <th scope=\"col\">Item Image</th>\r\n");
      out.write("                                        <th scope=\"col\">Price</th>\r\n");
      out.write("                                        <th scope=\"col\">Quantity</th>\r\n");
      out.write("                                        <th scope=\"col\">Total Price</th>\r\n");
      out.write("                                        <th scope=\"col\">Action</th>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </thead>\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                    ");
if(cu==null){ for (CartPojo item : cartItems) { 
      out.write("\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td>");
      out.print( item.getName() );
      out.write("</td>\r\n");
      out.write("                                        <td><img src=\"images/");
      out.print( item.getImage() );
      out.write("\" style=\"min-width:145px; max-height:80px; max-width:150px;\"></td>\r\n");
      out.write("                                        <td>&#8377; ");
      out.print( item.getPrice() );
      out.write("</td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <div class=\"text-center\">\r\n");
      out.write("                                                ");
      out.print( item.getQuantity() );
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td>&#8377; ");
      out.print( item.getTprice() );
      out.write("</td>\r\n");
      out.write("                                        <td><a href=\"deleteCart_servlet?cid=");
      out.print( item.getCid() );
      out.write("\"><button class=\"btn btn-danger\">Delete</button></a></td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    ");
 }}else{ 
                                  		List<CustomizePojo> lcc=customizeDaoimpl.getAllCustomizeByEmail(email);
                                  		for(CustomizePojo c:lcc){
                                    
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                     <tr>\r\n");
      out.write("                                        <td>Customize Cake</td>\r\n");
      out.write("                                        <td><img src=\"images/customize/");
      out.print(c.getImage() );
      out.write("\" style=\"min-width:145px; max-height:80px; max-width:150px;\"></td>\r\n");
      out.write("                                        <td>&#8377; 1200</td>\r\n");
      out.write("                                        <td>\r\n");
      out.write("                                            <div class=\"text-center\">\r\n");
      out.write("                                                1\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td>&#8377; 1200</td>\r\n");
      out.write("                                        <td>");
      out.print(c.getDetail() );
      out.write("</td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                    \r\n");
      out.write("                                    \r\n");
      out.write("                                    ");
} }
      out.write("\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("                            ");
if(cu==null){ 
      out.write("\r\n");
      out.write("                            <p style=\"text-align:right; font-size:20px; color:green;\">Total Price: <b id=\"totalPriceDisplay\">&#8377; ");
      out.print( totalPrice / 100 );
      out.write("</b></p>\r\n");
      out.write("                        ");
}else{
                        	totalPrice=120000;
                        	
      out.write("\r\n");
      out.write("                                                    <p style=\"text-align:right; font-size:20px; color:green;\">Total Price: <b id=\"totalPriceDisplay\">&#8377; 1200</b></p>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- Checkout Button -->\r\n");
      out.write("                <button id=\"checkoutBtn\" class=\"btn accordion-button btn-block mt-5\">Checkout</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"footer bg-light text-center py-3\">\r\n");
      out.write("    <p>&copy; 2025 Dummy Store. All Rights Reserved.</p>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("document.getElementById(\"checkoutBtn\").addEventListener(\"click\", function (e) {\r\n");
      out.write("    e.preventDefault();\r\n");
      out.write("\r\n");
      out.write("    var totalAmount = ");
      out.print( totalPrice );
      out.write("; // Get total price from JSP\r\n");
      out.write("    var options = {\r\n");
      out.write("        \"key\": \"rzp_test_5uPzGreHV3wiCs\", // Replace with your Razorpay Test Key\r\n");
      out.write("        \"amount\": totalAmount, \r\n");
      out.write("        \"currency\": \"INR\",\r\n");
      out.write("        \"name\": \"Dummy Store\",\r\n");
      out.write("        \"description\": \"Order Payment\",\r\n");
      out.write("        \"image\": \"https://yourlogo.com/logo.png\", // Optional: Your logo URL\r\n");
      out.write("        \"handler\": function (response) {\r\n");
      out.write("            alert(\"order placed suucessfully \\n Payment Successful! Payment ID: \" + response.razorpay_payment_id);\r\n");
      out.write("\r\n");
      out.write("            // Redirect to order confirmation page with payment details\r\n");
      out.write("            window.location.href = \"PlaceOrderServlet?payment_id=\" + response.razorpay_payment_id + \"&amount=\" + (totalAmount / 100);\r\n");
      out.write("        },\r\n");
      out.write("        \"prefill\": {\r\n");
      out.write("            \"email\": \"");
      out.print( email );
      out.write("\"\r\n");
      out.write("        },\r\n");
      out.write("        \"theme\": {\r\n");
      out.write("            \"color\": \"#ff5200\"\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    var rzp1 = new Razorpay(options);\r\n");
      out.write("    rzp1.open();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
