/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-04-07 11:59:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.daoimpl.UserDaoimpl;
import com.daoimpl.ProfileImpl;
import com.pojo.Profilepojo;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/message.jsp", Long.valueOf(1735911354380L));
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1737265382670L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.daoimpl.ProfileImpl");
    _jspx_imports_classes.add("com.daoimpl.UserDaoimpl");
    _jspx_imports_classes.add("com.pojo.Profilepojo");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Profile Page - Online Food Delivery</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css\" integrity=\"sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("  <style>\r\n");
      out.write("    * {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      font-family: Arial, sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    body {\r\n");
      out.write("      background-color: #f7f7f7;\r\n");
      out.write("      color: #333;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container {\r\n");
      out.write("      max-width: 1200px;\r\n");
      out.write("      margin: 20px auto;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      background-color: #fff;\r\n");
      out.write("      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile-header {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      gap: 20px;\r\n");
      out.write("      border-bottom: 2px solid #ddd;\r\n");
      out.write("      padding-bottom: 20px;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile-header img {\r\n");
      out.write("      width: 100px;\r\n");
      out.write("      height: 100px;\r\n");
      out.write("      border-radius: 50%;\r\n");
      out.write("      border: 3px solid #f56a6a;\r\n");
      out.write("      object-fit: cover;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile-header .user-info {\r\n");
      out.write("      flex: 1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile-header .user-info h2 {\r\n");
      out.write("      font-size: 24px;\r\n");
      out.write("      margin-bottom: 8px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .profile-header .user-info p {\r\n");
      out.write("      color: #777;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .tabs {\r\n");
      out.write("      display: flex;\r\n");
      out.write("      gap: 20px;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      border-bottom: 2px solid #ddd;\r\n");
      out.write("      padding-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .tabs button {\r\n");
      out.write("      background-color: transparent;\r\n");
      out.write("      border: none;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      color: #333;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      border-bottom: 2px solid transparent;\r\n");
      out.write("      transition: all 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .tabs button.active {\r\n");
      out.write("      color: #f56a6a;\r\n");
      out.write("      border-bottom: 2px solid #f56a6a;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .tab-content {\r\n");
      out.write("      display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .tab-content.active {\r\n");
      out.write("      display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .order-history,\r\n");
      out.write("    .address-book,\r\n");
      out.write("    .settings {\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      border: 1px solid #ddd;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      background-color: #f9f9f9;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .order-history ul,\r\n");
      out.write("    .address-book ul {\r\n");
      out.write("      list-style: none;\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .order-history ul li,\r\n");
      out.write("    .address-book ul li {\r\n");
      out.write("      padding: 10px 0;\r\n");
      out.write("      border-bottom: 1px solid #ddd;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .order-history ul li:last-child,\r\n");
      out.write("    .address-book ul li:last-child {\r\n");
      out.write("      border-bottom: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .settings label {\r\n");
      out.write("      display: block;\r\n");
      out.write("      margin-bottom: 10px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .settings input[type=\"text\"],\r\n");
      out.write("    .settings input[type=\"email\"],\r\n");
      out.write("    .settings input[type=\"password\"] {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      border: 1px solid #ddd;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .settings button {\r\n");
      out.write("      background-color: #f56a6a;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      border: none;\r\n");
      out.write("      padding: 10px 20px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      transition: background-color 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .settings button:hover {\r\n");
      out.write("      background-color: #e55555;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("        <a href=\"\" class=\"logo\"><img src=\"images/logo.png\" alt=\"\"></a>\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">Home</a>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">Cakes</a>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">Customize Cakes</a>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">About Us</a>\r\n");
      out.write("            <a href=\"index.jsp\" class=\"text-decoration-none\">Contact Us</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"icons\">\r\n");
      out.write("            <div class=\"search-icon\"><i class=\"fa-solid fa-magnifying-glass\"></i></div>\r\n");
      out.write("            <a href=\"cart.jsp\"><div class=\"cart-icon\"><i class=\"fa-solid fa-cart-arrow-down\"></i></div></a>\r\n");
      out.write("            <div class=\"menu-icon\"><i class=\"fa-solid fa-bars\"></i></div>\r\n");
      out.write("            <!-- <a href=\"registration.html\">\r\n");
      out.write("                <div class=\"login-icon\"><i class=\"fa-solid fa-user\"></i></div>\r\n");
      out.write("            </a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"search-form\">\r\n");
      out.write("            <input type=\"search\" name=\"search\" id=\"search-box\" placeholder=\"search here...\">\r\n");
      out.write("            <label for=\"search-box\" class=\"fa-solid fa-magnifying-glass\"></label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cart-items-container\">\r\n");
      out.write("            <!-- first item -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"brownie.webp\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>brownie</h1>\r\n");
      out.write("                    <div class=\"price\">rs99/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- second item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"pcake.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>pineapple Cake</h1>\r\n");
      out.write("                    <div class=\"price\">rs300/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- third item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"ccake.jpeg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>choclate Cake</h1>\r\n");
      out.write("                    <div class=\"price\">rs450/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- fourth item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"cball.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>choclate balls</h3>\r\n");
      out.write("                    <div class=\"price\">rs200/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"\" class=\"btn\">order now</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write('\r');
      out.write('\n');

String email12=(String)session.getAttribute("email");
ProfileImpl profileimpl=new ProfileImpl();
Profilepojo lp=profileimpl.getProfileByEmail(email12);
UserDaoimpl userDaoimpl12=new UserDaoimpl();
String username12=userDaoimpl12.getUsernameByEmail(email12);
/* Userimpl userimpl12=new Userimpl();
String username12=userimpl12.getUsernameByEmail(email12);
Profileimpl profileimpl=new Profileimpl();
Profilepojo lp=profileimpl.getProfileByEmail(email12);
String add=request.getParameter("add");
Orderimpl orderimpl=new Orderimpl();
List<OrderPojo> lo=orderimpl.getOrderByEmail(email12);
System.out.println(lp.getCity()); */

      out.write("\r\n");
      out.write("  <div class=\"container\" style=\"margin-top: 100px\">\r\n");
      out.write("    <!-- Profile Header -->\r\n");
      out.write("    ");

String msg=(String)session.getAttribute("msg");
if(msg!=null){

      out.write("\r\n");
      out.write("<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("  <strong>");
      out.print(msg );
      out.write("</strong> \r\n");
      out.write("  <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
}
session.removeAttribute("msg");

      out.write("\r\n");
      out.write("    ");

    if(lp.getEmail()==null){
    
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("    <div class=\"col-md-5\">\r\n");
      out.write("    <div class=\"text-center\">\r\n");
      out.write("    <h4> Welcome <b>");
      out.print(username12 );
      out.write("</b></h4>\r\n");
      out.write("    <button onclick=\"toggle()\" style=\"background-color:#ff5200;color: white;padding: 5px 30px;font-size: 20px;font-weight: 900;border:1px solid white;border-radius:7px; \">Add Profile</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-7\">\r\n");
      out.write("    <h4 id=\"message\">Profile has not been added</h4>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"profile\" class=\"card\" style=\"display: none;\">\r\n");
      out.write("    <div class=\"card-body\">\r\n");
      out.write("    <form action=\"Addprofile_servlet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">Name</label>\r\n");
      out.write("    <input type=\"text\" name=\"name\" required=\"required\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Enter Name\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputPassword1\">Contact</label>\r\n");
      out.write("    <input type=\"tel\" name=\"contact\" required=\"required\" class=\"form-control\" id=\"exampleInputPassword1\" placeholder=\"Password\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleFormControlSelect1\">State</label>\r\n");
      out.write("    <select class=\"form-control\" name=\"state\" id=\"exampleFormControlSelect1\">\r\n");
      out.write("    <option>select state</option>\r\n");
      out.write("       <option value=\"Andhra Pradesh\">Andhra Pradesh</option>\r\n");
      out.write("            <option value=\"Arunachal Pradesh\">Arunachal Pradesh</option>\r\n");
      out.write("            <option value=\"Assam\">Assam</option>\r\n");
      out.write("            <option value=\"Bihar\">Bihar</option>\r\n");
      out.write("            <option value=\"Chhattisgarh\">Chhattisgarh</option>\r\n");
      out.write("            <option value=\"Goa\">Goa</option>\r\n");
      out.write("            <option value=\"Gujarat\">Gujarat</option>\r\n");
      out.write("            <option value=\"Haryana\">Haryana</option>\r\n");
      out.write("            <option value=\"Himachal Pradesh\">Himachal Pradesh</option>\r\n");
      out.write("            <option value=\"Jharkhand\">Jharkhand</option>\r\n");
      out.write("            <option value=\"Karnataka\">Karnataka</option>\r\n");
      out.write("            <option value=\"Kerala\">Kerala</option>\r\n");
      out.write("            <option value=\"Madhya Pradesh\">Madhya Pradesh</option>\r\n");
      out.write("            <option value=\"Maharashtra\">Maharashtra</option>\r\n");
      out.write("            <option value=\"Manipur\">Manipur</option>\r\n");
      out.write("            <option value=\"Meghalaya\">Meghalaya</option>\r\n");
      out.write("            <option value=\"Mizoram\">Mizoram</option>\r\n");
      out.write("            <option value=\"Nagaland\">Nagaland</option>\r\n");
      out.write("            <option value=\"Odisha\">Odisha</option>\r\n");
      out.write("            <option value=\"Punjab\">Punjab</option>\r\n");
      out.write("            <option value=\"Rajasthan\">Rajasthan</option>\r\n");
      out.write("            <option value=\"Sikkim\">Sikkim</option>\r\n");
      out.write("            <option value=\"Tamil Nadu\">Tamil Nadu</option>\r\n");
      out.write("            <option value=\"Telangana\">Telangana</option>\r\n");
      out.write("            <option value=\"Tripura\">Tripura</option>\r\n");
      out.write("            <option value=\"Uttar Pradesh\">Uttar Pradesh</option>\r\n");
      out.write("            <option value=\"Uttarakhand\">Uttarakhand</option>\r\n");
      out.write("            <option value=\"West Bengal\">West Bengal</option>\r\n");
      out.write("            <option value=\"Andaman and Nicobar Islands\">Andaman and Nicobar Islands</option>\r\n");
      out.write("            <option value=\"Chandigarh\">Chandigarh</option>\r\n");
      out.write("            <option value=\"Dadra and Nagar Haveli and Daman and Diu\">Dadra and Nagar Haveli and Daman and Diu</option>\r\n");
      out.write("            <option value=\"Lakshadweep\">Lakshadweep</option>\r\n");
      out.write("            <option value=\"Delhi\">Delhi</option>\r\n");
      out.write("            <option value=\"Puducherry\">Puducherry</option>\r\n");
      out.write("       \r\n");
      out.write("    </select>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">City</label>\r\n");
      out.write("    <input type=\"text\" name=\"city\" required=\"required\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Enter City\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">Street</label>\r\n");
      out.write("    <input type=\"text\" name=\"street\" required=\"required\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Enter house no,Bulding name,street\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">Pincode</label>\r\n");
      out.write("    <input type=\"number\" name=\"pincode\" required=\"required\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Enter pincode\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleInputEmail1\">Landmark</label>\r\n");
      out.write("    <input type=\"text\" name=\"landmark\" required=\"required\" class=\"form-control\" id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\" placeholder=\"Enter Landmark\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <label for=\"exampleFormControlFile1\">Image</label>\r\n");
      out.write("    <input type=\"file\" name=\"image\" class=\"form-control-file\" id=\"exampleFormControlFile1\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <button type=\"submit\" class=\"btn nav-color text-white btn-block\">Submit</button>\r\n");
      out.write("</form>\r\n");
      out.write("    \r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");
}else{ 
    
    
      out.write("\r\n");
      out.write("    <div class=\"profile-header\">\r\n");
      out.write("      <img src=\"images/");
      out.print(lp.getImage() );
      out.write("\" alt=\"User Profile Picture\">\r\n");
      out.write("     \r\n");
      out.write("      <div class=\"user-info\">\r\n");
      out.write("        <h2>");
      out.print(lp.getName());
      out.write("</h2>\r\n");
      out.write("        <p>Email:");
      out.print(lp.getEmail());
      out.write("</p>\r\n");
      out.write("        <p>Phone: +");
      out.print(lp.getContact() );
      out.write("</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("     <a href=\"editprofile.jsp\"> <button class=\"btn nav-color px-5 text-white\">edit</button></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Tabs -->\r\n");
      out.write("    <div class=\"tabs\">\r\n");
      out.write("      <button class=\"tab-btn active\" onclick=\"switchTab('order-history')\">Order History</button>\r\n");
      out.write("      <button class=\"tab-btn\" onclick=\"switchTab('address-book')\">Address Book</button>\r\n");
      out.write("      <button class=\"tab-btn\" onclick=\"switchTab('settings')\">Account Settings</button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Tab Content -->\r\n");
      out.write("    <div id=\"order-history\" class=\"tab-content active\">\r\n");
      out.write("      <div class=\"order-history\">\r\n");
      out.write("        <h3>Your Recent Orders</h3>\r\n");
      out.write("        <table class=\"table\">\r\n");
      out.write("  <thead>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th scope=\"col\">Id</th>\r\n");
      out.write("      <th scope=\"col\">Name</th>\r\n");
      out.write("      <th scope=\"col\">Price</th>\r\n");
      out.write("      <th scope=\"col\">Quantity</th>\r\n");
      out.write("      <th scope=\"col\">Total-Price</th>\r\n");
      out.write("      <th scope=\"col\">Date</th>\r\n");
      out.write("      <th scope=\"col\">Status</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </thead>\r\n");
      out.write("  <tbody>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("  </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"address-book\" class=\"tab-content \">\r\n");
      out.write("      <div class=\"address-book d-flex\">\r\n");
      out.write("      <div style=\"width: 60%\">\r\n");
      out.write("        <h3>Saved Addresses</h3>\r\n");
      out.write("        <ul id=\"address-list\">\r\n");
      out.write("          <li class=\"address-item\">\r\n");
      out.write("            <span>");
      out.print(lp.getStreet() );
      out.write(',');
      out.print(lp.getCity() );
      out.write(',');
      out.print(lp.getPincode() );
      out.print(lp.getState() );
      out.write("  \r\n");
      out.write("           </span>\r\n");
      out.write("            <p>Landmark:-<b>");
      out.print(lp.getLandmark() );
      out.write("</b></p>\r\n");
      out.write("            \r\n");
      out.write("           </div>\r\n");
      out.write("           <div style=\"width: 40%\">\r\n");
      out.write("          <!-- <a href=\"updateAddress.jsp\"><button class=\"btn btn-danger mx-5\" >edit</button></a>\r\n");
      out.write("             <button class=\"btn btn-danger\" >Delete</button> -->\r\n");
      out.write("           </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("           \r\n");
      out.write("            <div class=\"address-actions\">\r\n");
      out.write("              \r\n");
      out.write("             \r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("          ");
      out.write("\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("<!--                <a href=\"addAddress.jsp\"> <button class=\"btn nav-color text-white\" style=\"width: 100%\" >Add New Address</button></a>\r\n");
      out.write(" -->                </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"settings\" class=\"tab-content\">\r\n");
      out.write("      <div class=\"settings\">\r\n");
      out.write("        <h3>Update Account Settings</h3>\r\n");
      out.write("        <form>\r\n");
      out.write("          <label for=\"name\">Name</label>\r\n");
      out.write("          <input type=\"text\" id=\"name\" placeholder=\"Enter your name\">\r\n");
      out.write("          <label for=\"email\">Email</label>\r\n");
      out.write("          <input type=\"email\" id=\"email\" placeholder=\"Enter your email\">\r\n");
      out.write("          <label for=\"password\">Password</label>\r\n");
      out.write("          <input type=\"password\" id=\"password\" placeholder=\"Enter new password\">\r\n");
      out.write("          <button type=\"submit\">Save Changes</button>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <script>\r\n");
      out.write("  function toggle(){\r\n");
      out.write("	  $(\"#message\").hide();\r\n");
      out.write("      $(\"#profile\").show();\r\n");
      out.write("  }\r\n");
      out.write("    function switchTab(tabId) {\r\n");
      out.write("    	\r\n");
      out.write("    	if(tabId==\"order-history\"){\r\n");
      out.write("    		$(\"#order-history\").show();\r\n");
      out.write("    		$(\"#address-book\").hide();\r\n");
      out.write("    		$(\"#settings\").hide();\r\n");
      out.write("    	}\r\n");
      out.write("    	else if(tabId==\"settings\"){\r\n");
      out.write("    		$(\"#order-history\").hide();\r\n");
      out.write("    		$(\"#address-book\").hide();\r\n");
      out.write("    		$(\"#settings\").show();\r\n");
      out.write("    	}\r\n");
      out.write("    	else{\r\n");
      out.write("    		$(\"#order-history\").hide();\r\n");
      out.write("    		$(\"#address-book\").show();\r\n");
      out.write("    		$(\"#settings\").hide();\r\n");
      out.write("    	}\r\n");
      out.write("      // Remove active class from all tabs and contents\r\n");
      out.write("      document.querySelectorAll('.tab-btn').forEach((btn) => btn.classList.remove('active'));\r\n");
      out.write("      document.querySelectorAll('.tab-content').forEach((content) => content.classList.remove('active'));\r\n");
      out.write("\r\n");
      out.write("      // Add active class to selected tab and content\r\n");
      out.write("     /*  document.querySelector(`[onclick=\"switchTab('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tabId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\"]`).classList.add('active');\r\n");
      out.write("      document.getElementById(tabId).classList.add('active'); */\r\n");
      out.write("      \r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
