/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-01-15 14:28:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/74366baee4.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("\r\n");
      out.write("    <title>Registration Form</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --main-color: rgb(102, 67, 67);\r\n");
      out.write("            --nav-color: rgb(121, 87, 87);\r\n");
      out.write("            --bg-color: rgb(255, 240, 209);\r\n");
      out.write("            --black: rgb(59, 48, 48);\r\n");
      out.write("            --card-color: rgb(66, 36, 8);\r\n");
      out.write("            --theme: rgb(230, 201, 185);\r\n");
      out.write("            --border: 0.1rem solid var(--card-color);\r\n");
      out.write("            --box-shadow: 0 0 20px rgb(0, 0, 0);\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: overlock;\r\n");
      out.write("            background-color: var(--bg-color);\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            margin: 100px auto;\r\n");
      out.write("            background: var(--black);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: var(--box-shadow);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: var(--bg-color);\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-size: 35px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: var(--bg-color);\r\n");
      out.write("            margin: 15px 0 5px;\r\n");
      out.write("            font-size: 19px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container input {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("            border: var(--border);\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            padding-left: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container button {\r\n");
      out.write("            margin-left: 190px;\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 17px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            background: var(--main-color);\r\n");
      out.write("            color: var(--bg-color);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container button:hover {\r\n");
      out.write("            background: var(--nav-color);\r\n");
      out.write("            letter-spacing: 0.1rem;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container .redirect {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("        .form-container .redirect1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: var(--nav-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container .redirect a {\r\n");
      out.write("            color: var(--bg-color);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container .redirect a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <a href=\"\" class=\"logo\"><img src=\"images/logo.png\" alt=\"\"></a>\r\n");
      out.write("        <nav class=\"navbar\">\r\n");
      out.write("            <a href=\"index.jsp\">Home</a>\r\n");
      out.write("            <a href=\"index.jsp\">Cakes</a>\r\n");
      out.write("            <a href=\"index.jsp\">Customize Cakes</a>\r\n");
      out.write("            <a href=\"index.jsp\">About Us</a>\r\n");
      out.write("            <a href=\"index.jsp\">Contact Us</a>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"icons\">\r\n");
      out.write("            <div class=\"search-icon\"><i class=\"fa-solid fa-magnifying-glass\"></i></div>\r\n");
      out.write("            <div class=\"cart-icon\"><i class=\"fa-solid fa-cart-arrow-down\"></i></div>\r\n");
      out.write("            <div class=\"menu-icon\"><i class=\"fa-solid fa-bars\"></i></div>\r\n");
      out.write("            <!-- <a href=\"registration.html\">\r\n");
      out.write("                <div class=\"login-icon\"><i class=\"fa-solid fa-user\"></i></div>\r\n");
      out.write("            </a> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"search-form\">\r\n");
      out.write("            <input type=\"search\" name=\"search\" id=\"search-box\" placeholder=\"search here...\">\r\n");
      out.write("            <label for=\"search-box\" class=\"fa-solid fa-magnifying-glass\"></label>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cart-items-container\">\r\n");
      out.write("            <!-- first item -->\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"brownie.webp\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>brownie</h1>\r\n");
      out.write("                    <div class=\"price\">rs99/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- second item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"pcake.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>pineapple Cake</h1>\r\n");
      out.write("                    <div class=\"price\">rs300/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- third item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"ccake.jpeg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h1>choclate Cake</h1>\r\n");
      out.write("                    <div class=\"price\">rs450/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- fourth item -->\r\n");
      out.write("            <div class=\"cart-item\">\r\n");
      out.write("                <span class=\"fas fa-times\"></span>\r\n");
      out.write("                <img src=\"cball.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                    <h3>choclate balls</h3>\r\n");
      out.write("                    <div class=\"price\">rs200/-</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"\" class=\"btn\">order now</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"form-container\">\r\n");
      out.write("        <h2>Registration Form</h2>\r\n");
      out.write("        <form action=\"User_servlet\" method=\"POST\">\r\n");
      out.write("            <label for=\"name\">First Name</label>\r\n");
      out.write("            <input type=\"text\" id=\"fname\" name=\"fname\" placeholder=\"Enter your first name\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"name\">Last Name</label>\r\n");
      out.write("            <input type=\"text\" id=\"lname\" name=\"lname\" placeholder=\"Enter your last name\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"name\">Mobile Number</label>\r\n");
      out.write("            <input type=\"tel\" id=\"mno\" name=\"mno\" placeholder=\"Enter your mobile number\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"email\">Email</label>\r\n");
      out.write("            <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Enter your email\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"password\">Password</label>\r\n");
      out.write("            <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Enter your password\" required>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\">Register</button>\r\n");
      out.write("        </form>\r\n");
      out.write("        <div class=\"redirect\">\r\n");
      out.write("            <h5 class=\"redirect1\">Already registered? <a href=\"login.jsp\">Login here</a></h5>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
