/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-04-02 12:29:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.daoimpl.UserDaoimpl;
import com.pojo.UserPojo;
import com.pojo.CakePojo;
import com.daoimpl.CakeDaoimpl;

public final class updateUser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/message.jsp", Long.valueOf(1735911354380L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("com.pojo.UserPojo");
    _jspx_imports_classes.add("com.daoimpl.CakeDaoimpl");
    _jspx_imports_classes.add("com.pojo.CakePojo");
    _jspx_imports_classes.add("com.daoimpl.UserDaoimpl");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Update Cake</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/74366baee4.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("\r\n");
      out.write("    <title>Registration Form</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --main-color: rgb(102, 67, 67);\r\n");
      out.write("            --nav-color: rgb(121, 87, 87);\r\n");
      out.write("            --bg-color: rgb(255, 240, 209);\r\n");
      out.write("            --black: rgb(59, 48, 48);\r\n");
      out.write("            --card-color: rgb(66, 36, 8);\r\n");
      out.write("            --theme: rgb(230, 201, 185);\r\n");
      out.write("            --border: 0.1rem solid var(--card-color);\r\n");
      out.write("            --box-shadow: 0 0 20px rgb(0, 0, 0);\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: overlock;\r\n");
      out.write("            background-color: var(--bg-color);\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            margin: 100px auto;\r\n");
      out.write("            background: var(--black);\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: var(--box-shadow);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container h2 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: var(--bg-color);\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-size: 35px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            color: var(--bg-color);\r\n");
      out.write("            margin: 15px 0 5px;\r\n");
      out.write("            font-size: 19px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container input {\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("            border: var(--border);\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            padding-left: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container button {\r\n");
      out.write("            margin-left: 190px;\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            font-size: 17px;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            background: var(--main-color);\r\n");
      out.write("            color: var(--bg-color);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container button:hover {\r\n");
      out.write("            background: var(--nav-color);\r\n");
      out.write("            letter-spacing: 0.1rem;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container .redirect {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("        .form-container .redirect1 {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: var(--nav-color);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container .redirect a {\r\n");
      out.write("            color: var(--bg-color);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container .redirect a:hover {\r\n");
      out.write("            text-decoration: underline;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

int cid=Integer.parseInt(request .getParameter("cid"));
UserDaoimpl userDaoimpl=new UserDaoimpl();
UserPojo userPojo=userDaoimpl.getUserById(cid);

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div class=\"form-container\">\r\n");
      out.write(" ");

String msg=(String)session.getAttribute("msg");
if(msg!=null){

      out.write("\r\n");
      out.write("<div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("  <strong>");
      out.print(msg );
      out.write("</strong> \r\n");
      out.write("  <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
}
session.removeAttribute("msg");

      out.write("\r\n");
      out.write("        <h2>Edit User</h2>\r\n");
      out.write("        <form action=\"UpdateUser_servlet?uid=");
      out.print(cid );
      out.write("\" method=\"POST\">\r\n");
      out.write("            <label for=\"name\">First Name</label>\r\n");
      out.write("            <input type=\"text\" id=\"fname\" value=\"");
      out.print(userPojo.getFname() );
      out.write("\" name=\"fname\" placeholder=\"Enter your first name\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"name\">Last Name</label>\r\n");
      out.write("            <input type=\"text\" id=\"lname\" name=\"lname\" value=\"");
      out.print(userPojo.getLname() );
      out.write("\" placeholder=\"Enter your last name\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"name\">Mobile Number</label>\r\n");
      out.write("            <input type=\"tel\" id=\"mno\" name=\"mno\" value=\"");
      out.print(userPojo.getConatct() );
      out.write("\" placeholder=\"Enter your mobile number\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"email\">Email</label>\r\n");
      out.write("            <input type=\"email\" id=\"email\" value=\"");
      out.print(userPojo.getEmail() );
      out.write("\" name=\"email\" placeholder=\"Enter your email\" required>\r\n");
      out.write("\r\n");
      out.write("            <label for=\"password\">Password</label>\r\n");
      out.write("            <input type=\"password\" id=\"password\" value=\"");
      out.print(userPojo.getPassword() );
      out.write("\" name=\"password\" placeholder=\"Enter your password\" required>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <button type=\"submit\">Update</button>\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
